version: '3.1'

services:
  db:
    image: mysql
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: f1_db
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    volumes:
      - my-datavolume:/var/lib/mysql
    ports:
      - "3306:3306"
volumes:
  my-datavolume: